spring:
  application:
    name: microservice-sidecar
server:
  port: 8481
eureka:
  client:
    healthCheck:
      enabled: true
    service-url:
      defaultZone: http://alex:becauseofyou7@47.104.84.122:9093/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  config: classpath:logback.xml
ribbon:
  ServerListRefreshInterval: 5000
  ReadTimeout: 60000
  ConnectTimeout: 60000
management:
  endpoints:
    web:
      exposure:
        include: "*"
sidecar:
  port: 8060
  health-uri: http://localhost:8060/health.json