server:
  port: 8600
logging:
  config: classpath:logback.xml
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://alex:becauseofyou7@47.104.84.122:9093/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-ribbon_hystrix
#ribbon:
#  eureka:
#    enabled: false
#microservice-provider-user:
#  ribbon:
#    listOfServers: localhost:8476
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# set hystrix timeout time
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ServerListRefreshInterval: 5000