server:
  port: 8473
  servlet:
      context-path: /consumer_movie
logging:
  config: classpath:logback.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:aabbcc@localhost:8472/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie
#ribbon:
#  eureka:
#    enabled: false
microservice-provider-user:
  ribbon:
#    listOfServers: localhost:8476
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule