server:
  port: 8502
  servlet:
      context-path: /consumer_movie_feign_hystrix
logging:
  config: classpath:logback.xml
#  level:
#    com.springcloud.maincloud.feign.MovieFeignClient2: DEBUG
#    com.springcloud.maincloud.feign.MovieFeignClient: DEBUG
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://alex:becauseofyou7@47.104.84.122:9093/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie_feign_hystrix
#ribbon:
#  eureka:
#    enabled: false
#microservice-provider-user:
#  ribbon:
#    listOfServers: localhost:8476
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#set the Hystrix timeout time
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
  hystrix:
    enabled: true