server:
  port: 8502
logging:
  config: classpath:logback.xml
#  level:
#    com.springcloud.maincloud.feign.MovieFeignClient2: DEBUG
#    com.springcloud.maincloud.feign.MovieFeignClient: DEBUG
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://alex:becauseofyou7@47.104.84.122:9093/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie_feign_hystrix
ribbon:
  ServerListRefreshInterval: 5000
#ribbon:
#  eureka:
#    enabled: false
#microservice-provider-user:
#  ribbon:
#    listOfServers: localhost:8476
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#set the Hystrix timeout time
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false
feign:
  hystrix:
    enabled: true