spring:
  application:
    name: zuul-filters
server:
  port: 8482
eureka:
  client:
    healthCheck:
      enabled: true
    service-url:
      defaultZone: http://alex:becauseofyou7@47.104.84.122:9093/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  config: classpath:logback.xml
ribbon:
  ServerListRefreshInterval: 5000
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    user-proxy:
      path: /feign/**
      serviceId: microservice-consumer-movie_feign_hystrix
management:
  endpoints:
    web:
      exposure:
        include: "*"
hystrix:
  command:
      default:
        execution:
          timeout:
            enabled: false