server:
  port: 8472
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:aabbcc@localhost:8472/eureka/
logging:
  config: classpath:logback.xml
